source 'https://rubygems.org'

gem 'aws-sdk-cloudformation'
gem 'aws-sdk-ec2'
gem 'azure_mgmt_compute'
gem 'azure_mgmt_network'
gem 'azure_mgmt_resources'
gem 'colorize'
gem 'commander'
gem 'google-cloud-resource_manager'
gem 'ipaddr'
gem 'rspec'
gem 'rspec'
gem 'rspec-wait'
gem 'terminal-table'
gem 'whirly'
