#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/cloudware.rb'

include Cloudware::WithSpinner
result = with_spinner('Spinning') do
  sleep 10
  'I am the results string'
end
puts result
