source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'pg'
gem 'require_all'
gem 'standalone_migrations'

group :test do
  gem 'rspec'
  # Install from Git to get access to features like testing `optional`
  # relationships (https://github.com/thoughtbot/shoulda-matchers/issues/1069).
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
end

group :development do
  gem 'pry'
end
