source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'pg'
gem 'require_all'
gem 'standalone_migrations'

group :test do
  gem 'rspec'
end

group :development do
  gem 'pry'
end
