#!/bin/bash
#==============================================================================
# Copyright (C) 2007-2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Cloudware.
#
# Alces Cloudware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Cloudware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Cloudware, please visit:
# https://github.com/alces-software/cloudware
#==============================================================================
source=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
dep_source="fresh"
target=/opt/cloudware
log_file=/var/log/cloudware.log
os=$1
source $source/scripts/lib/ui.functions.sh
source $source/scripts/lib/fetch.functions.sh
source $source/scripts/lib/install.functions.sh
deps="ruby bundler"

cat <<EOF
[33m===============================================================================
 STARTING INSTALLATION
===============================================================================[0m
EOF

mkdir -p ${source}/tmp/log ${source}/tmp/src ${source}/tmp/build
dep_logs="${source}/tmp/log"
dep_build="${source}/tmp/build"
dep_src="${source}/tmp/src"

title 'Configuring system'
doing 'Creating example configuration file'
if [[ ! -f $HOME/.cloudware.yml ]]; then
  cat << EOF > $HOME/.cloudware.yml
---
general:
  log_file: '/var/log/cloudware.log'

provider:
  aws:
    access_key_id: ''
    secret_access_key: ''
  azure:
    tenant_id: ''
    subscription_id: ''
    client_secret: ''
    client_id: ''
EOF
fi
say_done $?
doing 'Creating log file'
if [[ ! -f $log_file ]]; then
  touch $log_file
  chmod 644 $log_file
fi
say_done $?

title 'Creating initial directory structure'
doing 'Create'
mkdir -p /opt/cloudware
cp -R "${source}/"{Gemfile,Gemfile.lock,bin,lib,providers} "${target}"
say_done $?


title 'Installing required packages'
for dep in ${deps}; do
  source "${source}/scripts/dependencies/${dep}.sh"
  if ! detect_${dep}; then
    fetch_${dep}
    install_${dep}
  fi
done

cat <<EOF
[33m
===============================================================================
 INSTALLATION COMPLETE
===============================================================================
[0m[1m
Execute 'cloudware --help' for further information.
[0m
EOF
